version: '3.7'
services:
  coctohug-flax:
    image: raingggg/coctohug-flax:develop
    container_name: coctohug-flax
    restart: always
    networks:
      - coctohug-network
    volumes:
      - ~/.coctohug:/root/.coctohug
      - ~/.coctohug-flax:/root/.chia
      - /d1:/plots1
      - /d2:/plots2
      - /d3:/plots3
    environment:
      - TZ=Asia/Shanghai
      - mode=fullnode
      - controller_address=192.168.123.23
      - worker_address=192.168.123.23
      - plots_dir=/plots1:/plots2:/plots3
    ports:
      - 12653:12653
      - 6888:6888
      - 6885:6885

networks:
  coctohug-network:
    name: coctohug-app-network

